# -- ruff
-   id: ruff
    name: ruff
    description: "Run 'ruff' for extremely fast Python linting"
    entry: ruff check --force-exclude
    language: python
    types_or: [python, pyi, jupyter]
    args: [ --fix, --config=./config/ruff.toml ]
    require_serial: true
    additional_dependencies: []
    minimum_pre_commit_version: "2.9.2"

-   id: ruff-format
    name: ruff-format
    description: "Run 'ruff format' for extremely fast Python formatting"
    entry: ruff format --force-exclude
    language: python
    types_or: [python, pyi, jupyter]
    args: []
    require_serial: true
    additional_dependencies: []
    minimum_pre_commit_version: "2.9.2"

# -- biome
-   id: biome-ci
    name: biome ci
    entry: biome ci --files-ignore-unknown=true --no-errors-on-unmatched --config=./config/biome.json
    language: node
    types: [text]
    files: "\\.(jsx?|tsx?|c(js|ts)|m(js|ts)|d\\.(ts|cts|mts)|jsonc?|css|svelte|vue|astro|graphql|gql)$"
    require_serial: true

-   id: biome-check
    name: biome check
    entry: biome check --write --files-ignore-unknown=true --no-errors-on-unmatched --config=./config/biome.json
    language: node
    types: [text]
    files: "\\.(jsx?|tsx?|c(js|ts)|m(js|ts)|d\\.(ts|cts|mts)|jsonc?|css|svelte|vue|astro|graphql|gql)$"
    require_serial: true

-   id: biome-format
    name: biome format
    entry: biome format --write --files-ignore-unknown=true --no-errors-on-unmatched --config=./config/biome.json
    language: node
    types: [text]
    files: "\\.(jsx?|tsx?|c(js|ts)|m(js|ts)|d\\.(ts|cts|mts)|jsonc?|css|svelte|vue|astro|graphql|gql)$"
    require_serial: true

-   id: biome-lint
    name: biome lint
    entry: biome lint --write --files-ignore-unknown=true --no-errors-on-unmatched --config=./config/biome.json
    language: node
    types: [text]
    files: "\\.(jsx?|tsx?|c(js|ts)|m(js|ts)|d\\.(ts|cts|mts)|jsonc?|css|svelte|vue|astro|graphql|gql)$"
    require_serial: true
